# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Creative\GitHub\Maya-Utility-App\assets\UI\Interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1104, 709)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.266, y1:0.273, x2:0.805, y2:0.704818, stop:0 rgba(147, 101, 200, 255), stop:0.919753 rgba(86, 120, 200, 255));\n"
"border-radius: 10;")
        self.centralwidget.setObjectName("centralwidget")
        self.drop_shadow_layout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.drop_shadow_layout.setContentsMargins(10, 10, 10, 10)
        self.drop_shadow_layout.setSpacing(0)
        self.drop_shadow_layout.setObjectName("drop_shadow_layout")
        self.drop_shadow_frame = QtWidgets.QFrame(self.centralwidget)
        self.drop_shadow_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.drop_shadow_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.drop_shadow_frame.setObjectName("drop_shadow_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.drop_shadow_frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_bar = QtWidgets.QFrame(self.drop_shadow_frame)
        self.title_bar.setMaximumSize(QtCore.QSize(16777215, 50))
        self.title_bar.setStyleSheet("background-color:none;")
        self.title_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.title_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_bar.setObjectName("title_bar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.title_bar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_title = QtWidgets.QFrame(self.title_bar)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.frame_title.setFont(font)
        self.frame_title.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_title.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_title.setObjectName("frame_title")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_title)
        self.verticalLayout_2.setContentsMargins(25, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.app_title = QtWidgets.QLabel(self.frame_title)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.app_title.setFont(font)
        self.app_title.setStyleSheet("")
        self.app_title.setObjectName("app_title")
        self.verticalLayout_2.addWidget(self.app_title, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout.addWidget(self.frame_title, 0, QtCore.Qt.AlignTop)
        self.frame_btns = QtWidgets.QFrame(self.title_bar)
        self.frame_btns.setMaximumSize(QtCore.QSize(150, 16777215))
        self.frame_btns.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_btns.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_btns.setObjectName("frame_btns")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_btns)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_minimize = QtWidgets.QPushButton(self.frame_btns)
        self.btn_minimize.setMinimumSize(QtCore.QSize(24, 24))
        self.btn_minimize.setMaximumSize(QtCore.QSize(24, 24))
        self.btn_minimize.setStyleSheet("QPushButton {\n"
"    border:none;\n"
"    border-radius: 12px;\n"
"    background-color: rgb(85, 255, 127);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(85, 255, 127, 150);\n"
"}")
        self.btn_minimize.setText("")
        self.btn_minimize.setObjectName("btn_minimize")
        self.horizontalLayout_2.addWidget(self.btn_minimize)
        self.btn_maximize = QtWidgets.QPushButton(self.frame_btns)
        self.btn_maximize.setMinimumSize(QtCore.QSize(24, 24))
        self.btn_maximize.setMaximumSize(QtCore.QSize(24, 24))
        self.btn_maximize.setStyleSheet("QPushButton {\n"
"    border:none;\n"
"    border-radius: 12px;\n"
"    background-color: rgb(255, 146, 73);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 146, 73, 150);\n"
"}")
        self.btn_maximize.setText("")
        self.btn_maximize.setObjectName("btn_maximize")
        self.horizontalLayout_2.addWidget(self.btn_maximize)
        self.btn_close = QtWidgets.QPushButton(self.frame_btns)
        self.btn_close.setMinimumSize(QtCore.QSize(24, 24))
        self.btn_close.setMaximumSize(QtCore.QSize(24, 24))
        self.btn_close.setStyleSheet("QPushButton {\n"
"    border:none;\n"
"    border-radius: 12px;\n"
"    background-color: rgb(255, 62, 62);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 62, 62, 150);\n"
"}")
        self.btn_close.setText("")
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout_2.addWidget(self.btn_close)
        self.horizontalLayout.addWidget(self.frame_btns, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignTop)
        self.verticalLayout.addWidget(self.title_bar)
        self.contents = QtWidgets.QFrame(self.drop_shadow_frame)
        self.contents.setStyleSheet("background-color:none;")
        self.contents.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contents.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contents.setObjectName("contents")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.contents)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame = QtWidgets.QFrame(self.contents)
        self.frame.setStyleSheet("background-color: rgba(0,0,0,0.8)")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_5.addWidget(self.frame)
        self.verticalLayout.addWidget(self.contents)
        self.credits_bar = QtWidgets.QFrame(self.drop_shadow_frame)
        self.credits_bar.setMinimumSize(QtCore.QSize(0, 30))
        self.credits_bar.setMaximumSize(QtCore.QSize(16777215, 30))
        self.credits_bar.setStyleSheet("background-color:none;")
        self.credits_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.credits_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.credits_bar.setObjectName("credits_bar")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.credits_bar)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.credit_frame = QtWidgets.QFrame(self.credits_bar)
        self.credit_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.credit_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.credit_frame.setObjectName("credit_frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.credit_frame)
        self.horizontalLayout_4.setContentsMargins(25, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.credit_label = QtWidgets.QLabel(self.credit_frame)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.credit_label.setFont(font)
        self.credit_label.setObjectName("credit_label")
        self.horizontalLayout_4.addWidget(self.credit_label)
        self.horizontalLayout_3.addWidget(self.credit_frame)
        self.grip_frame = QtWidgets.QFrame(self.credits_bar)
        self.grip_frame.setMinimumSize(QtCore.QSize(30, 30))
        self.grip_frame.setMaximumSize(QtCore.QSize(30, 30))
        self.grip_frame.setStyleSheet("padding: 5px;")
        self.grip_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.grip_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.grip_frame.setObjectName("grip_frame")
        self.horizontalLayout_3.addWidget(self.grip_frame)
        self.verticalLayout.addWidget(self.credits_bar)
        self.drop_shadow_layout.addWidget(self.drop_shadow_frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.app_title.setText(_translate("MainWindow", "Maya Utility App v1.0.0"))
        self.credit_label.setText(_translate("MainWindow", "Copyright @ Ajay Singh [Maya] 2022. All the rights are reserved."))
