# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\A00172\Desktop\New Utility\assets\UI\Interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 700)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\A00172\\Desktop\\New Utility\\assets\\UI\\../../../../.designer/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QMainWindow{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(51, 51, 51);\n"
"border-radius: 10;\n"
"color: rgb(255,255,255)")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.drop_shadow_frame = QtWidgets.QFrame(self.centralwidget)
        self.drop_shadow_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.drop_shadow_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.drop_shadow_frame.setObjectName("drop_shadow_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.drop_shadow_frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_bar = QtWidgets.QFrame(self.drop_shadow_frame)
        self.title_bar.setMaximumSize(QtCore.QSize(16777215, 50))
        self.title_bar.setStyleSheet("background-color:none;")
        self.title_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.title_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_bar.setObjectName("title_bar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.title_bar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_title = QtWidgets.QFrame(self.title_bar)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.frame_title.setFont(font)
        self.frame_title.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_title.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_title.setObjectName("frame_title")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_title)
        self.verticalLayout_2.setContentsMargins(25, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.app_title = QtWidgets.QLabel(self.frame_title)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.app_title.setFont(font)
        self.app_title.setStyleSheet("")
        self.app_title.setObjectName("app_title")
        self.verticalLayout_2.addWidget(self.app_title, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.horizontalLayout.addWidget(self.frame_title, 0, QtCore.Qt.AlignVCenter)
        self.frame_btns = QtWidgets.QFrame(self.title_bar)
        self.frame_btns.setMaximumSize(QtCore.QSize(150, 16777215))
        self.frame_btns.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_btns.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_btns.setObjectName("frame_btns")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_btns)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_minimize = QtWidgets.QPushButton(self.frame_btns)
        self.btn_minimize.setMinimumSize(QtCore.QSize(16, 16))
        self.btn_minimize.setMaximumSize(QtCore.QSize(16, 16))
        self.btn_minimize.setStyleSheet("QPushButton {\n"
"    border:none;\n"
"    border-radius: 8px;\n"
"    background-color: rgb(85, 255, 127);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(85, 255, 127, 150);\n"
"}")
        self.btn_minimize.setText("")
        self.btn_minimize.setObjectName("btn_minimize")
        self.horizontalLayout_2.addWidget(self.btn_minimize)
        self.btn_maximize = QtWidgets.QPushButton(self.frame_btns)
        self.btn_maximize.setMinimumSize(QtCore.QSize(16, 16))
        self.btn_maximize.setMaximumSize(QtCore.QSize(16, 16))
        self.btn_maximize.setStyleSheet("QPushButton {\n"
"    border:none;\n"
"    border-radius: 8px;\n"
"    background-color: rgb(255, 146, 73);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 146, 73, 150);\n"
"}")
        self.btn_maximize.setText("")
        self.btn_maximize.setObjectName("btn_maximize")
        self.horizontalLayout_2.addWidget(self.btn_maximize)
        self.btn_close = QtWidgets.QPushButton(self.frame_btns)
        self.btn_close.setMinimumSize(QtCore.QSize(16, 16))
        self.btn_close.setMaximumSize(QtCore.QSize(16, 16))
        self.btn_close.setStyleSheet("QPushButton {\n"
"    border:none;\n"
"    border-radius: 8px;\n"
"    background-color: rgb(255, 62, 62);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 62, 62, 150);\n"
"}")
        self.btn_close.setText("")
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout_2.addWidget(self.btn_close)
        self.horizontalLayout.addWidget(self.frame_btns, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignTop)
        self.verticalLayout.addWidget(self.title_bar)
        self.contents = QtWidgets.QFrame(self.drop_shadow_frame)
        self.contents.setStyleSheet("background-color:none;")
        self.contents.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.contents.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contents.setObjectName("contents")
        self.gridLayout = QtWidgets.QGridLayout(self.contents)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setVerticalSpacing(5)
        self.gridLayout.setObjectName("gridLayout")
        self.app_info_frame = QtWidgets.QFrame(self.contents)
        self.app_info_frame.setMinimumSize(QtCore.QSize(0, 150))
        self.app_info_frame.setMaximumSize(QtCore.QSize(16777215, 150))
        self.app_info_frame.setStyleSheet("border-radius: 0px;\n"
"border-top: 1px solid rgb(133, 133, 133);")
        self.app_info_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.app_info_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.app_info_frame.setObjectName("app_info_frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.app_info_frame)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.settings_menu = QtWidgets.QPushButton(self.app_info_frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.settings_menu.setFont(font)
        self.settings_menu.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.settings_menu.setStyleSheet("QPushButton{\n"
"    background-color: rgba(223, 223, 221, 150);\n"
"    color: rgb(0,0,0);\n"
"    padding: 10px;\n"
"    margin: 5px;\n"
"    border-top-left-radius: 8px;\n"
"    border-bottom-left-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(223, 223, 221, 200);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgba(223, 223, 221, 200);\n"
"    border-right: rgba(85, 0, 255, 150) 4px solid;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/settings.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settings_menu.setIcon(icon1)
        self.settings_menu.setObjectName("settings_menu")
        self.verticalLayout_5.addWidget(self.settings_menu)
        self.help_menu = QtWidgets.QPushButton(self.app_info_frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.help_menu.setFont(font)
        self.help_menu.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.help_menu.setStyleSheet("QPushButton{\n"
"    background-color: rgba(223, 223, 221, 150);\n"
"    color: rgb(0,0,0);\n"
"    padding: 10px;\n"
"    margin: 5px;\n"
"    border-top-left-radius: 8px;\n"
"    border-bottom-left-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(223, 223, 221, 200);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgba(223, 223, 221, 200);\n"
"    border-right: rgba(85, 0, 255, 150) 4px solid;\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/help-circle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.help_menu.setIcon(icon2)
        self.help_menu.setObjectName("help_menu")
        self.verticalLayout_5.addWidget(self.help_menu)
        self.about_menu = QtWidgets.QPushButton(self.app_info_frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.about_menu.setFont(font)
        self.about_menu.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.about_menu.setStyleSheet("QPushButton{\n"
"    background-color: rgba(223, 223, 221, 150);\n"
"    color: rgb(0,0,0);\n"
"    padding: 10px;\n"
"    margin: 5px;\n"
"    border-top-left-radius: 8px;\n"
"    border-bottom-left-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(223, 223, 221, 200);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgba(223, 223, 221, 200);\n"
"    border-right: rgba(85, 0, 255, 150) 4px solid;\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/info.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.about_menu.setIcon(icon3)
        self.about_menu.setObjectName("about_menu")
        self.verticalLayout_5.addWidget(self.about_menu)
        self.gridLayout.addWidget(self.app_info_frame, 2, 0, 1, 1)
        self.brand_frame = QtWidgets.QFrame(self.contents)
        self.brand_frame.setMinimumSize(QtCore.QSize(25, 75))
        self.brand_frame.setMaximumSize(QtCore.QSize(75, 75))
        self.brand_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.brand_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.brand_frame.setObjectName("brand_frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.brand_frame)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.brand_logo = QtWidgets.QLabel(self.brand_frame)
        self.brand_logo.setText("")
        self.brand_logo.setPixmap(QtGui.QPixmap("c:\\Users\\A00172\\Desktop\\New Utility\\assets\\UI\\../../../../.designer/icon.ico"))
        self.brand_logo.setScaledContents(True)
        self.brand_logo.setAlignment(QtCore.Qt.AlignCenter)
        self.brand_logo.setObjectName("brand_logo")
        self.horizontalLayout_5.addWidget(self.brand_logo)
        self.gridLayout.addWidget(self.brand_frame, 0, 0, 1, 1)
        self.content_frame = QtWidgets.QFrame(self.contents)
        self.content_frame.setStyleSheet("background-color: rgb(29, 29, 29);\n"
"border-radius: 0px;")
        self.content_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content_frame.setObjectName("content_frame")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.content_frame)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.main_content_pages = QtWidgets.QStackedWidget(self.content_frame)
        font = QtGui.QFont()
        font.setItalic(False)
        self.main_content_pages.setFont(font)
        self.main_content_pages.setStyleSheet("\n"
"QLineEdit{\n"
"    border: none;\n"
"    border-Bottom: 2px solid #5e5e5e;\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    border-Bottom: 2px solid #7e7e7e;\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"    border-Bottom: 2px solid #7e7e7e;\n"
"}")
        self.main_content_pages.setObjectName("main_content_pages")
        self.dashboard = QtWidgets.QWidget()
        self.dashboard.setObjectName("dashboard")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.dashboard)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(5)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_2 = QtWidgets.QLabel(self.dashboard)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_8.addWidget(self.label_2)
        self.main_content_pages.addWidget(self.dashboard)
        self.utilites_number = QtWidgets.QWidget()
        self.utilites_number.setObjectName("utilites_number")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.utilites_number)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.input_number = QtWidgets.QFrame(self.utilites_number)
        self.input_number.setMinimumSize(QtCore.QSize(0, 40))
        self.input_number.setMaximumSize(QtCore.QSize(16777215, 60))
        self.input_number.setStyleSheet("QFrame{\n"
"    padding: 5px;\n"
"}\n"
"\n"
"")
        self.input_number.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.input_number.setFrameShadow(QtWidgets.QFrame.Raised)
        self.input_number.setObjectName("input_number")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.input_number)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.number_input_label = QtWidgets.QLabel(self.input_number)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.number_input_label.setFont(font)
        self.number_input_label.setObjectName("number_input_label")
        self.horizontalLayout_9.addWidget(self.number_input_label)
        self.num_input = QtWidgets.QLineEdit(self.input_number)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setItalic(True)
        self.num_input.setFont(font)
        self.num_input.setAutoFillBackground(False)
        self.num_input.setStyleSheet("")
        self.num_input.setInputMask("")
        self.num_input.setText("")
        self.num_input.setPlaceholderText("Number to Convert")
        self.num_input.setClearButtonEnabled(False)
        self.num_input.setObjectName("num_input")
        self.horizontalLayout_9.addWidget(self.num_input)
        self.clear_btn = QtWidgets.QPushButton(self.input_number)
        self.clear_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.clear_btn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/x.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clear_btn.setIcon(icon4)
        self.clear_btn.setObjectName("clear_btn")
        self.horizontalLayout_9.addWidget(self.clear_btn)
        self.copy_num_all_btn = QtWidgets.QPushButton(self.input_number)
        self.copy_num_all_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.copy_num_all_btn.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/copy.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.copy_num_all_btn.setIcon(icon5)
        self.copy_num_all_btn.setObjectName("copy_num_all_btn")
        self.horizontalLayout_9.addWidget(self.copy_num_all_btn)
        self.convert_btn = QtWidgets.QPushButton(self.input_number)
        self.convert_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.convert_btn.setStyleSheet("QPushButton{\n"
"    padding: 10px;\n"
"    border-radius: 8px;\n"
"    background-color: rgba(152, 152, 151, 200);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border-radius: 4px;\n"
"    background-color: rgba(152, 152, 151, 150);\n"
"}")
        self.convert_btn.setObjectName("convert_btn")
        self.horizontalLayout_9.addWidget(self.convert_btn)
        self.verticalLayout_10.addWidget(self.input_number)
        self.output_number = QtWidgets.QFrame(self.utilites_number)
        self.output_number.setStyleSheet("QLineEdit{\n"
"    border:none;\n"
"}")
        self.output_number.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.output_number.setFrameShadow(QtWidgets.QFrame.Raised)
        self.output_number.setObjectName("output_number")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.output_number)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.number_output = QtWidgets.QGridLayout()
        self.number_output.setContentsMargins(10, 10, 10, 10)
        self.number_output.setHorizontalSpacing(10)
        self.number_output.setObjectName("number_output")
        self.decimal_lbl = QtWidgets.QLabel(self.output_number)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.decimal_lbl.setFont(font)
        self.decimal_lbl.setObjectName("decimal_lbl")
        self.number_output.addWidget(self.decimal_lbl, 3, 0, 1, 1)
        self.eng_lbl = QtWidgets.QLabel(self.output_number)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.eng_lbl.setFont(font)
        self.eng_lbl.setObjectName("eng_lbl")
        self.number_output.addWidget(self.eng_lbl, 1, 0, 1, 1)
        self.nep_words_copy_btn = QtWidgets.QPushButton(self.output_number)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.nep_words_copy_btn.setFont(font)
        self.nep_words_copy_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.nep_words_copy_btn.setText("")
        self.nep_words_copy_btn.setIcon(icon5)
        self.nep_words_copy_btn.setObjectName("nep_words_copy_btn")
        self.number_output.addWidget(self.nep_words_copy_btn, 8, 2, 1, 1)
        self.nepali_disp = QtWidgets.QLineEdit(self.output_number)
        self.nepali_disp.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.nepali_disp.setFont(font)
        self.nepali_disp.setObjectName("nepali_disp")
        self.number_output.addWidget(self.nepali_disp, 2, 1, 1, 1)
        self.whole_lbl = QtWidgets.QLabel(self.output_number)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.whole_lbl.setFont(font)
        self.whole_lbl.setObjectName("whole_lbl")
        self.number_output.addWidget(self.whole_lbl, 4, 0, 1, 1)
        self.lakh_copy_btn = QtWidgets.QPushButton(self.output_number)
        self.lakh_copy_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lakh_copy_btn.setText("")
        self.lakh_copy_btn.setIcon(icon5)
        self.lakh_copy_btn.setObjectName("lakh_copy_btn")
        self.number_output.addWidget(self.lakh_copy_btn, 5, 2, 1, 1)
        self.num_copy_btn = QtWidgets.QPushButton(self.output_number)
        self.num_copy_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.num_copy_btn.setText("")
        self.num_copy_btn.setIcon(icon5)
        self.num_copy_btn.setObjectName("num_copy_btn")
        self.number_output.addWidget(self.num_copy_btn, 0, 2, 1, 1)
        self.words_nep_disp = QtWidgets.QLabel(self.output_number)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.words_nep_disp.setFont(font)
        self.words_nep_disp.setText("")
        self.words_nep_disp.setWordWrap(True)
        self.words_nep_disp.setObjectName("words_nep_disp")
        self.number_output.addWidget(self.words_nep_disp, 8, 1, 1, 1)
        self.words_nep_lbl = QtWidgets.QLabel(self.output_number)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.words_nep_lbl.setFont(font)
        self.words_nep_lbl.setObjectName("words_nep_lbl")
        self.number_output.addWidget(self.words_nep_lbl, 8, 0, 1, 1)
        self.nep_copy_btn = QtWidgets.QPushButton(self.output_number)
        self.nep_copy_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.nep_copy_btn.setText("")
        self.nep_copy_btn.setIcon(icon5)
        self.nep_copy_btn.setObjectName("nep_copy_btn")
        self.number_output.addWidget(self.nep_copy_btn, 2, 2, 1, 1)
        self.lakh_lbl = QtWidgets.QLabel(self.output_number)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.lakh_lbl.setFont(font)
        self.lakh_lbl.setObjectName("lakh_lbl")
        self.number_output.addWidget(self.lakh_lbl, 5, 0, 1, 1)
        self.nepali_lbl = QtWidgets.QLabel(self.output_number)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.nepali_lbl.setFont(font)
        self.nepali_lbl.setObjectName("nepali_lbl")
        self.number_output.addWidget(self.nepali_lbl, 2, 0, 1, 1)
        self.number_disp = QtWidgets.QLineEdit(self.output_number)
        self.number_disp.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.number_disp.setFont(font)
        self.number_disp.setObjectName("number_disp")
        self.number_output.addWidget(self.number_disp, 0, 1, 1, 1)
        self.num_lbl = QtWidgets.QLabel(self.output_number)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.num_lbl.setFont(font)
        self.num_lbl.setObjectName("num_lbl")
        self.number_output.addWidget(self.num_lbl, 0, 0, 1, 1)
        self.decimal_disp = QtWidgets.QLineEdit(self.output_number)
        self.decimal_disp.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.decimal_disp.setFont(font)
        self.decimal_disp.setObjectName("decimal_disp")
        self.number_output.addWidget(self.decimal_disp, 3, 1, 1, 1)
        self.eng_words_copy_btn = QtWidgets.QPushButton(self.output_number)
        self.eng_words_copy_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.eng_words_copy_btn.setText("")
        self.eng_words_copy_btn.setIcon(icon5)
        self.eng_words_copy_btn.setObjectName("eng_words_copy_btn")
        self.number_output.addWidget(self.eng_words_copy_btn, 7, 2, 1, 1)
        self.words_eng_lbl = QtWidgets.QLabel(self.output_number)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.words_eng_lbl.setFont(font)
        self.words_eng_lbl.setObjectName("words_eng_lbl")
        self.number_output.addWidget(self.words_eng_lbl, 7, 0, 1, 1)
        self.whole_disp = QtWidgets.QLineEdit(self.output_number)
        self.whole_disp.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.whole_disp.setFont(font)
        self.whole_disp.setObjectName("whole_disp")
        self.number_output.addWidget(self.whole_disp, 4, 1, 1, 1)
        self.million_lbl = QtWidgets.QLabel(self.output_number)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.million_lbl.setFont(font)
        self.million_lbl.setObjectName("million_lbl")
        self.number_output.addWidget(self.million_lbl, 6, 0, 1, 1)
        self.whole_copy_btn = QtWidgets.QPushButton(self.output_number)
        self.whole_copy_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.whole_copy_btn.setText("")
        self.whole_copy_btn.setIcon(icon5)
        self.whole_copy_btn.setObjectName("whole_copy_btn")
        self.number_output.addWidget(self.whole_copy_btn, 4, 2, 1, 1)
        self.words_eng_disp = QtWidgets.QLabel(self.output_number)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.words_eng_disp.setFont(font)
        self.words_eng_disp.setText("")
        self.words_eng_disp.setWordWrap(True)
        self.words_eng_disp.setObjectName("words_eng_disp")
        self.number_output.addWidget(self.words_eng_disp, 7, 1, 1, 1)
        self.lakh_format_disp = QtWidgets.QLineEdit(self.output_number)
        self.lakh_format_disp.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.lakh_format_disp.setFont(font)
        self.lakh_format_disp.setObjectName("lakh_format_disp")
        self.number_output.addWidget(self.lakh_format_disp, 5, 1, 1, 1)
        self.million_format_disp = QtWidgets.QLineEdit(self.output_number)
        self.million_format_disp.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.million_format_disp.setFont(font)
        self.million_format_disp.setObjectName("million_format_disp")
        self.number_output.addWidget(self.million_format_disp, 6, 1, 1, 1)
        self.eng_copy_btn = QtWidgets.QPushButton(self.output_number)
        self.eng_copy_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.eng_copy_btn.setText("")
        self.eng_copy_btn.setIcon(icon5)
        self.eng_copy_btn.setObjectName("eng_copy_btn")
        self.number_output.addWidget(self.eng_copy_btn, 1, 2, 1, 1)
        self.million_copy_btn = QtWidgets.QPushButton(self.output_number)
        self.million_copy_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.million_copy_btn.setText("")
        self.million_copy_btn.setIcon(icon5)
        self.million_copy_btn.setObjectName("million_copy_btn")
        self.number_output.addWidget(self.million_copy_btn, 6, 2, 1, 1)
        self.decimal_copy_btn = QtWidgets.QPushButton(self.output_number)
        self.decimal_copy_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.decimal_copy_btn.setText("")
        self.decimal_copy_btn.setIcon(icon5)
        self.decimal_copy_btn.setObjectName("decimal_copy_btn")
        self.number_output.addWidget(self.decimal_copy_btn, 3, 2, 1, 1)
        self.english_disp = QtWidgets.QLineEdit(self.output_number)
        self.english_disp.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.english_disp.setFont(font)
        self.english_disp.setObjectName("english_disp")
        self.number_output.addWidget(self.english_disp, 1, 1, 1, 1)
        self.verticalLayout_11.addLayout(self.number_output)
        self.verticalLayout_10.addWidget(self.output_number, 0, QtCore.Qt.AlignTop)
        self.main_content_pages.addWidget(self.utilites_number)
        self.join_pdf_container = QtWidgets.QWidget()
        self.join_pdf_container.setObjectName("join_pdf_container")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.join_pdf_container)
        self.verticalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_22.setSpacing(0)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.pdf_merger_output = QtWidgets.QFrame(self.join_pdf_container)
        self.pdf_merger_output.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.pdf_merger_output.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pdf_merger_output.setObjectName("pdf_merger_output")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.pdf_merger_output)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.verticalLayout_22.addWidget(self.pdf_merger_output)
        self.files_input_pdf_merger = QtWidgets.QFrame(self.join_pdf_container)
        self.files_input_pdf_merger.setMinimumSize(QtCore.QSize(0, 40))
        self.files_input_pdf_merger.setMaximumSize(QtCore.QSize(16777215, 60))
        self.files_input_pdf_merger.setStyleSheet("QPushButton{\n"
"    padding: 10px;\n"
"    border-radius: 8px;\n"
"    background-color: rgba(152, 152, 151, 200);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border-radius: 4px;\n"
"    background-color: rgba(152, 152, 151, 150);\n"
"}")
        self.files_input_pdf_merger.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.files_input_pdf_merger.setFrameShadow(QtWidgets.QFrame.Raised)
        self.files_input_pdf_merger.setObjectName("files_input_pdf_merger")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.files_input_pdf_merger)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.add_pdf_files_btn = QtWidgets.QPushButton(self.files_input_pdf_merger)
        self.add_pdf_files_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/file-plus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_pdf_files_btn.setIcon(icon6)
        self.add_pdf_files_btn.setObjectName("add_pdf_files_btn")
        self.horizontalLayout_12.addWidget(self.add_pdf_files_btn)
        self.remove_pdf_file_btn = QtWidgets.QPushButton(self.files_input_pdf_merger)
        self.remove_pdf_file_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/icons/file-minus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.remove_pdf_file_btn.setIcon(icon7)
        self.remove_pdf_file_btn.setObjectName("remove_pdf_file_btn")
        self.horizontalLayout_12.addWidget(self.remove_pdf_file_btn)
        self.clear_pdf_btn = QtWidgets.QPushButton(self.files_input_pdf_merger)
        self.clear_pdf_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/icons/x-square.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clear_pdf_btn.setIcon(icon8)
        self.clear_pdf_btn.setObjectName("clear_pdf_btn")
        self.horizontalLayout_12.addWidget(self.clear_pdf_btn)
        self.pdf_move_up_btn = QtWidgets.QPushButton(self.files_input_pdf_merger)
        self.pdf_move_up_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/icons/chevrons-up.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pdf_move_up_btn.setIcon(icon9)
        self.pdf_move_up_btn.setObjectName("pdf_move_up_btn")
        self.horizontalLayout_12.addWidget(self.pdf_move_up_btn)
        self.pdf_move_down_btn = QtWidgets.QPushButton(self.files_input_pdf_merger)
        self.pdf_move_down_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/icons/chevrons-down.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pdf_move_down_btn.setIcon(icon10)
        self.pdf_move_down_btn.setObjectName("pdf_move_down_btn")
        self.horizontalLayout_12.addWidget(self.pdf_move_down_btn)
        self.save_pdf_btn = QtWidgets.QPushButton(self.files_input_pdf_merger)
        self.save_pdf_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/icons/save.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save_pdf_btn.setIcon(icon11)
        self.save_pdf_btn.setObjectName("save_pdf_btn")
        self.horizontalLayout_12.addWidget(self.save_pdf_btn)
        self.verticalLayout_22.addWidget(self.files_input_pdf_merger)
        self.main_content_pages.addWidget(self.join_pdf_container)
        self.image_text_extraction_page = DropZone()
        self.image_text_extraction_page.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.image_text_extraction_page.setMouseTracking(False)
        self.image_text_extraction_page.setObjectName("image_text_extraction_page")
        self.verticalLayout_221 = QtWidgets.QVBoxLayout(self.image_text_extraction_page)
        self.verticalLayout_221.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_221.setSpacing(0)
        self.verticalLayout_221.setObjectName("verticalLayout_221")
        self.image_drop_zone = QtWidgets.QFrame(self.image_text_extraction_page)
        self.image_drop_zone.setMinimumSize(QtCore.QSize(0, 40))
        self.image_drop_zone.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.image_drop_zone.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.image_drop_zone.setStyleSheet("QPushButton{\n"
"    padding: 10px;\n"
"    border-radius: 8px;\n"
"    background-color: rgba(152, 152, 151, 200);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border-radius: 4px;\n"
"    background-color: rgba(152, 152, 151, 150);\n"
"}")
        self.image_drop_zone.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.image_drop_zone.setFrameShadow(QtWidgets.QFrame.Raised)
        self.image_drop_zone.setObjectName("image_drop_zone")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.image_drop_zone)
        self.verticalLayout_24.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout_24.setSpacing(0)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.image_drop_border = QtWidgets.QFrame(self.image_drop_zone)
        self.image_drop_border.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.image_drop_border.setAcceptDrops(True)
        self.image_drop_border.setStyleSheet("QFrame{\n"
"    border: 2px dashed  rgb(125, 125, 124);\n"
"    border-radius: 4px;\n"
"}")
        self.image_drop_border.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.image_drop_border.setFrameShadow(QtWidgets.QFrame.Raised)
        self.image_drop_border.setObjectName("image_drop_border")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.image_drop_border)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.select_file_btn = QtWidgets.QPushButton(self.image_drop_border)
        self.select_file_btn.setMinimumSize(QtCore.QSize(150, 0))
        self.select_file_btn.setMaximumSize(QtCore.QSize(250, 16777215))
        self.select_file_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.select_file_btn.setObjectName("select_file_btn")
        self.horizontalLayout_11.addWidget(self.select_file_btn)
        self.Image_Label = QtWidgets.QLabel(self.image_drop_border)
        self.Image_Label.setObjectName("Image_Label")
        self.horizontalLayout_11.addWidget(self.Image_Label, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_24.addWidget(self.image_drop_border)
        self.verticalLayout_221.addWidget(self.image_drop_zone)
        self.text_extracted_disp = QtWidgets.QFrame(self.image_text_extraction_page)
        self.text_extracted_disp.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.text_extracted_disp.setFrameShadow(QtWidgets.QFrame.Raised)
        self.text_extracted_disp.setObjectName("text_extracted_disp")
        self.verticalLayout_231 = QtWidgets.QVBoxLayout(self.text_extracted_disp)
        self.verticalLayout_231.setObjectName("verticalLayout_231")
        self.extracted_texts = QtWidgets.QTextBrowser(self.text_extracted_disp)
        self.extracted_texts.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.extracted_texts.setReadOnly(False)
        self.extracted_texts.setMarkdown("")
        self.extracted_texts.setObjectName("extracted_texts")
        self.verticalLayout_231.addWidget(self.extracted_texts)
        self.verticalLayout_221.addWidget(self.text_extracted_disp)
        self.main_content_pages.addWidget(self.image_text_extraction_page)
        self.tax_pan_search = QtWidgets.QWidget()
        self.tax_pan_search.setObjectName("tax_pan_search")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.tax_pan_search)
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20.setSpacing(0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.pan_input_container = QtWidgets.QFrame(self.tax_pan_search)
        self.pan_input_container.setMinimumSize(QtCore.QSize(0, 40))
        self.pan_input_container.setMaximumSize(QtCore.QSize(16777215, 60))
        self.pan_input_container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.pan_input_container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pan_input_container.setObjectName("pan_input_container")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.pan_input_container)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.pan_input_label = QtWidgets.QLabel(self.pan_input_container)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.pan_input_label.setFont(font)
        self.pan_input_label.setObjectName("pan_input_label")
        self.horizontalLayout_10.addWidget(self.pan_input_label)
        self.pan_input = QtWidgets.QLineEdit(self.pan_input_container)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.pan_input.setFont(font)
        self.pan_input.setAutoFillBackground(False)
        self.pan_input.setStyleSheet("")
        self.pan_input.setText("")
        self.pan_input.setPlaceholderText("")
        self.pan_input.setClearButtonEnabled(False)
        self.pan_input.setObjectName("pan_input")
        self.horizontalLayout_10.addWidget(self.pan_input)
        self.clear_pan_btn = QtWidgets.QPushButton(self.pan_input_container)
        self.clear_pan_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.clear_pan_btn.setText("")
        self.clear_pan_btn.setIcon(icon4)
        self.clear_pan_btn.setObjectName("clear_pan_btn")
        self.horizontalLayout_10.addWidget(self.clear_pan_btn)
        self.copy_pan_raw_btn = QtWidgets.QPushButton(self.pan_input_container)
        self.copy_pan_raw_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.copy_pan_raw_btn.setText("")
        self.copy_pan_raw_btn.setIcon(icon5)
        self.copy_pan_raw_btn.setObjectName("copy_pan_raw_btn")
        self.horizontalLayout_10.addWidget(self.copy_pan_raw_btn)
        self.pan_search_btn = QtWidgets.QPushButton(self.pan_input_container)
        self.pan_search_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pan_search_btn.setStyleSheet("padding: 10px;\n"
"border-radius: 8px;\n"
"background-color: rgb(152, 152, 151);")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icons/icons/search.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pan_search_btn.setIcon(icon12)
        self.pan_search_btn.setObjectName("pan_search_btn")
        self.horizontalLayout_10.addWidget(self.pan_search_btn)
        self.verticalLayout_20.addWidget(self.pan_input_container)
        self.pan_output = QtWidgets.QTabWidget(self.tax_pan_search)
        self.pan_output.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pan_output.setStyleSheet("QTabWidget::pane {\n"
"    border: 1px solid rgb(51, 51, 51);\n"
"      padding: 2px;\n"
"    background-color: rgba(51, 51, 51,200);\n"
"} \n"
"\n"
"QTabBar::tab {\n"
"    background-color: rgba(47, 47, 47,200);\n"
"     border: 1px solid rgb(51, 51, 51);\n"
"    padding: 10px;\n"
"} \n"
"\n"
"QTabBar::tab:selected { \n"
"   background-color: rgba(47, 47, 47,150);\n"
"  margin-bottom: -1px; \n"
"}\n"
"\n"
"QTabBar::tab:hover { \n"
"   background-color: rgba(47, 47, 47,150);\n"
"}")
        self.pan_output.setObjectName("pan_output")
        self.pan_table_output_page = QtWidgets.QWidget()
        self.pan_table_output_page.setObjectName("pan_table_output_page")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.pan_table_output_page)
        self.verticalLayout_27.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_27.setSpacing(5)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.pan_table_output = QtWidgets.QTableWidget(self.pan_table_output_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pan_table_output.sizePolicy().hasHeightForWidth())
        self.pan_table_output.setSizePolicy(sizePolicy)
        self.pan_table_output.setStyleSheet("QTableWidget{\n"
"    background-color: rgb(47, 47, 47);\n"
"    alternate-background-color: rgb(40, 40, 40);\n"
"}\n"
"\n"
"QTableWidget QTableCornerButton::section {\n"
"    background-color: #646464;\n"
"    border-style: none;\n"
"    border: 1px solid #fffff8;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #646464;\n"
"    padding: 5px;\n"
"    font-size: 10pt;\n"
"    border-style: none;\n"
"    border: 1px solid #fffff8;\n"
"}\n"
"\n"
"QHeaderView::section:horizontal\n"
"{\n"
"    border-top: 1px solid #fffff8;\n"
"}\n"
"\n"
"QHeaderView::section:vertical\n"
"{\n"
"    border-left: 1px solid #fffff8;\n"
"}")
        self.pan_table_output.setAlternatingRowColors(True)
        self.pan_table_output.setShowGrid(True)
        self.pan_table_output.setGridStyle(QtCore.Qt.DashDotLine)
        self.pan_table_output.setCornerButtonEnabled(True)
        self.pan_table_output.setColumnCount(1)
        self.pan_table_output.setObjectName("pan_table_output")
        self.pan_table_output.setRowCount(12)
        item = QtWidgets.QTableWidgetItem()
        self.pan_table_output.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.pan_table_output.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.pan_table_output.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.pan_table_output.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.pan_table_output.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.pan_table_output.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.pan_table_output.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.pan_table_output.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.pan_table_output.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.pan_table_output.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.pan_table_output.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.pan_table_output.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.pan_table_output.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.pan_table_output.setItem(0, 0, item)
        self.pan_table_output.horizontalHeader().setVisible(False)
        self.pan_table_output.horizontalHeader().setCascadingSectionResizes(False)
        self.pan_table_output.horizontalHeader().setDefaultSectionSize(100)
        self.pan_table_output.horizontalHeader().setMinimumSectionSize(50)
        self.pan_table_output.horizontalHeader().setStretchLastSection(True)
        self.pan_table_output.verticalHeader().setVisible(True)
        self.pan_table_output.verticalHeader().setStretchLastSection(True)
        self.verticalLayout_27.addWidget(self.pan_table_output)
        self.pan_output.addTab(self.pan_table_output_page, "")
        self.raw_pan_out_page = QtWidgets.QWidget()
        self.raw_pan_out_page.setObjectName("raw_pan_out_page")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.raw_pan_out_page)
        self.verticalLayout_29.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_29.setSpacing(5)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.raw_output_container = QtWidgets.QScrollArea(self.raw_pan_out_page)
        self.raw_output_container.setWidgetResizable(True)
        self.raw_output_container.setObjectName("raw_output_container")
        self.raw_output_container_scrol = QtWidgets.QWidget()
        self.raw_output_container_scrol.setGeometry(QtCore.QRect(0, 0, 616, 420))
        self.raw_output_container_scrol.setObjectName("raw_output_container_scrol")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.raw_output_container_scrol)
        self.verticalLayout_28.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_28.setSpacing(5)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.raw_pan_output = QtWidgets.QLabel(self.raw_output_container_scrol)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.raw_pan_output.setFont(font)
        self.raw_pan_output.setObjectName("raw_pan_output")
        self.verticalLayout_28.addWidget(self.raw_pan_output, 0, QtCore.Qt.AlignTop)
        self.raw_output_container.setWidget(self.raw_output_container_scrol)
        self.verticalLayout_29.addWidget(self.raw_output_container)
        self.pan_output.addTab(self.raw_pan_out_page, "")
        self.verticalLayout_20.addWidget(self.pan_output)
        self.main_content_pages.addWidget(self.tax_pan_search)
        self.horizontalLayout_7.addWidget(self.main_content_pages)
        self.gridLayout.addWidget(self.content_frame, 1, 2, 2, 1)
        self.top_bar_frame = QtWidgets.QFrame(self.contents)
        self.top_bar_frame.setStyleSheet("background-color: rgb(37, 37, 38);\n"
"padding: 2px;")
        self.top_bar_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top_bar_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_bar_frame.setObjectName("top_bar_frame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.top_bar_frame)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.welcome_text = QtWidgets.QFrame(self.top_bar_frame)
        font = QtGui.QFont()
        font.setPointSize(2)
        self.welcome_text.setFont(font)
        self.welcome_text.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.welcome_text.setFrameShadow(QtWidgets.QFrame.Raised)
        self.welcome_text.setObjectName("welcome_text")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.welcome_text)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.welcome_label = QtWidgets.QLabel(self.welcome_text)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.welcome_label.setFont(font)
        self.welcome_label.setObjectName("welcome_label")
        self.verticalLayout_3.addWidget(self.welcome_label, 0, QtCore.Qt.AlignBottom)
        self.quotes_label = QtWidgets.QLabel(self.welcome_text)
        self.quotes_label.setMinimumSize(QtCore.QSize(0, 0))
        self.quotes_label.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setFamily("Kalam Light")
        font.setPointSize(10)
        font.setItalic(False)
        self.quotes_label.setFont(font)
        self.quotes_label.setScaledContents(True)
        self.quotes_label.setWordWrap(True)
        self.quotes_label.setObjectName("quotes_label")
        self.verticalLayout_3.addWidget(self.quotes_label, 0, QtCore.Qt.AlignVCenter)
        self.horizontalLayout_6.addWidget(self.welcome_text)
        self.date_frame = QtWidgets.QFrame(self.top_bar_frame)
        self.date_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.date_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.date_frame.setObjectName("date_frame")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.date_frame)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.groupBox = QtWidgets.QGroupBox(self.date_frame)
        self.groupBox.setObjectName("groupBox")
        self.dates_grid = QtWidgets.QGridLayout(self.groupBox)
        self.dates_grid.setObjectName("dates_grid")
        self.nepali_date = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(14)
        self.nepali_date.setFont(font)
        self.nepali_date.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.nepali_date.setObjectName("nepali_date")
        self.dates_grid.addWidget(self.nepali_date, 0, 0, 1, 1)
        self.intdt_copy_btn = QtWidgets.QPushButton(self.groupBox)
        self.intdt_copy_btn.setMinimumSize(QtCore.QSize(25, 0))
        self.intdt_copy_btn.setMaximumSize(QtCore.QSize(25, 16777215))
        self.intdt_copy_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.intdt_copy_btn.setText("")
        self.intdt_copy_btn.setIcon(icon5)
        self.intdt_copy_btn.setObjectName("intdt_copy_btn")
        self.dates_grid.addWidget(self.intdt_copy_btn, 1, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.int_date = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(14)
        self.int_date.setFont(font)
        self.int_date.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.int_date.setObjectName("int_date")
        self.dates_grid.addWidget(self.int_date, 1, 0, 1, 1)
        self.npdt_copy_btn = QtWidgets.QPushButton(self.groupBox)
        self.npdt_copy_btn.setMinimumSize(QtCore.QSize(25, 0))
        self.npdt_copy_btn.setMaximumSize(QtCore.QSize(25, 16777215))
        self.npdt_copy_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.npdt_copy_btn.setText("")
        self.npdt_copy_btn.setIcon(icon5)
        self.npdt_copy_btn.setObjectName("npdt_copy_btn")
        self.dates_grid.addWidget(self.npdt_copy_btn, 0, 1, 1, 1)
        self.verticalLayout_9.addWidget(self.groupBox)
        self.horizontalLayout_6.addWidget(self.date_frame)
        self.top_right_menu = QtWidgets.QFrame(self.top_bar_frame)
        self.top_right_menu.setMinimumSize(QtCore.QSize(150, 0))
        self.top_right_menu.setMaximumSize(QtCore.QSize(150, 16777215))
        self.top_right_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top_right_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_right_menu.setObjectName("top_right_menu")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.top_right_menu)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.np_cal_btn = QtWidgets.QPushButton(self.top_right_menu)
        self.np_cal_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.np_cal_btn.setStyleSheet("QPushButton{\n"
"    background-color: rgba(223, 223, 221, 150);\n"
"    color: rgb(0,0,0);\n"
"    padding: 10px;\n"
"    margin: 5px;\n"
"    border-top-left-radius: 8px;\n"
"    border-bottom-left-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(223, 223, 221, 200);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgba(223, 223, 221, 200);\n"
"    border-right: rgba(85, 0, 255, 150) 4px solid;\n"
"}")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/icons/icons/calendar.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.np_cal_btn.setIcon(icon13)
        self.np_cal_btn.setObjectName("np_cal_btn")
        self.horizontalLayout_8.addWidget(self.np_cal_btn)
        self.options_btn = QtWidgets.QPushButton(self.top_right_menu)
        self.options_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.options_btn.setStyleSheet("QPushButton{\n"
"    background-color: rgba(223, 223, 221, 150);\n"
"    color: rgb(0,0,0);\n"
"    padding: 10px;\n"
"    margin: 5px;\n"
"    border-top-left-radius: 8px;\n"
"    border-bottom-left-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(223, 223, 221, 200);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgba(223, 223, 221, 200);\n"
"    border-right: rgba(85, 0, 255, 150) 4px solid;\n"
"}")
        self.options_btn.setText("")
        self.options_btn.setIcon(icon1)
        self.options_btn.setObjectName("options_btn")
        self.horizontalLayout_8.addWidget(self.options_btn)
        self.horizontalLayout_6.addWidget(self.top_right_menu)
        self.gridLayout.addWidget(self.top_bar_frame, 0, 1, 1, 2)
        self.left_menu_frame = QtWidgets.QFrame(self.contents)
        self.left_menu_frame.setStyleSheet("padding: 0px;")
        self.left_menu_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.left_menu_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_menu_frame.setObjectName("left_menu_frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.left_menu_frame)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.dashboard_menu = QtWidgets.QPushButton(self.left_menu_frame)
        self.dashboard_menu.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.dashboard_menu.setFont(font)
        self.dashboard_menu.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dashboard_menu.setMouseTracking(False)
        self.dashboard_menu.setStyleSheet("QPushButton{\n"
"    background-color: rgba(223, 223, 221, 150);\n"
"    color: rgb(0,0,0);\n"
"    padding: 10px;\n"
"    margin: 5px;\n"
"    border-top-right-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(223, 223, 221, 200);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgba(223, 223, 221, 200);\n"
"    border-right: rgba(85, 0, 255, 150) 4px solid;\n"
"}")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/icons/icons/menu.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dashboard_menu.setIcon(icon14)
        self.dashboard_menu.setIconSize(QtCore.QSize(16, 16))
        self.dashboard_menu.setCheckable(True)
        self.dashboard_menu.setChecked(True)
        self.dashboard_menu.setAutoRepeat(False)
        self.dashboard_menu.setAutoDefault(True)
        self.dashboard_menu.setDefault(True)
        self.dashboard_menu.setFlat(False)
        self.dashboard_menu.setObjectName("dashboard_menu")
        self.verticalLayout_4.addWidget(self.dashboard_menu)
        self.utilities_menu = QtWidgets.QPushButton(self.left_menu_frame)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.utilities_menu.setFont(font)
        self.utilities_menu.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.utilities_menu.setStyleSheet("QPushButton{\n"
"    background-color: rgba(223, 223, 221, 150);\n"
"    color: rgb(0,0,0);\n"
"    padding: 10px;\n"
"    margin: 5px;\n"
"    border-top-right-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(223, 223, 221, 200);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgba(223, 223, 221, 200);\n"
"    border-right: rgba(85, 0, 255, 150) 4px solid;\n"
"}")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/icons/icons/tool.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.utilities_menu.setIcon(icon15)
        self.utilities_menu.setIconSize(QtCore.QSize(16, 16))
        self.utilities_menu.setCheckable(True)
        self.utilities_menu.setAutoRepeat(False)
        self.utilities_menu.setAutoDefault(False)
        self.utilities_menu.setDefault(False)
        self.utilities_menu.setFlat(False)
        self.utilities_menu.setObjectName("utilities_menu")
        self.verticalLayout_4.addWidget(self.utilities_menu)
        self.api_menu = QtWidgets.QPushButton(self.left_menu_frame)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.api_menu.setFont(font)
        self.api_menu.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.api_menu.setStyleSheet("QPushButton{\n"
"    background-color: rgba(223, 223, 221, 150);\n"
"    color: rgb(0,0,0);\n"
"    padding: 10px;\n"
"    margin: 5px;\n"
"    border-top-right-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(223, 223, 221, 200);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgba(223, 223, 221, 200);\n"
"    border-right: rgba(85, 0, 255, 150) 4px solid;\n"
"}")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/icons/icons/link.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.api_menu.setIcon(icon16)
        self.api_menu.setIconSize(QtCore.QSize(16, 16))
        self.api_menu.setCheckable(True)
        self.api_menu.setAutoRepeat(False)
        self.api_menu.setAutoDefault(False)
        self.api_menu.setDefault(False)
        self.api_menu.setFlat(False)
        self.api_menu.setObjectName("api_menu")
        self.verticalLayout_4.addWidget(self.api_menu)
        self.tax_menu = QtWidgets.QPushButton(self.left_menu_frame)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.tax_menu.setFont(font)
        self.tax_menu.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tax_menu.setStyleSheet("QPushButton{\n"
"    background-color: rgba(223, 223, 221, 150);\n"
"    color: rgb(0,0,0);\n"
"    padding: 10px;\n"
"    margin: 5px;\n"
"    border-top-right-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(223, 223, 221, 200);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgba(223, 223, 221, 200);\n"
"    border-right: rgba(85, 0, 255, 150) 4px solid;\n"
"}")
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/icons/icons/dollar-sign.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tax_menu.setIcon(icon17)
        self.tax_menu.setIconSize(QtCore.QSize(16, 16))
        self.tax_menu.setCheckable(True)
        self.tax_menu.setAutoRepeat(False)
        self.tax_menu.setAutoDefault(False)
        self.tax_menu.setDefault(False)
        self.tax_menu.setFlat(False)
        self.tax_menu.setObjectName("tax_menu")
        self.verticalLayout_4.addWidget(self.tax_menu)
        self.lms_menu = QtWidgets.QPushButton(self.left_menu_frame)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.lms_menu.setFont(font)
        self.lms_menu.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lms_menu.setStyleSheet("QPushButton{\n"
"    background-color: rgba(223, 223, 221, 150);\n"
"    color: rgb(0,0,0);\n"
"    padding: 10px;\n"
"    margin: 5px;\n"
"    border-top-right-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(223, 223, 221, 200);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgba(223, 223, 221, 200);\n"
"    border-right: rgba(85, 0, 255, 150) 4px solid;\n"
"}")
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/icons/icons/book.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.lms_menu.setIcon(icon18)
        self.lms_menu.setIconSize(QtCore.QSize(16, 16))
        self.lms_menu.setCheckable(True)
        self.lms_menu.setAutoRepeat(False)
        self.lms_menu.setAutoDefault(False)
        self.lms_menu.setDefault(False)
        self.lms_menu.setFlat(False)
        self.lms_menu.setObjectName("lms_menu")
        self.verticalLayout_4.addWidget(self.lms_menu)
        self.gridLayout.addWidget(self.left_menu_frame, 1, 0, 1, 1, QtCore.Qt.AlignTop)
        self.sub_menu_frame = QtWidgets.QFrame(self.contents)
        self.sub_menu_frame.setMinimumSize(QtCore.QSize(0, 0))
        self.sub_menu_frame.setMaximumSize(QtCore.QSize(175, 16777215))
        self.sub_menu_frame.setStyleSheet("background-color: rgb(37, 37, 38);\n"
"padding: 2px;\n"
"border-radius: 0px;")
        self.sub_menu_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sub_menu_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sub_menu_frame.setObjectName("sub_menu_frame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.sub_menu_frame)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.submenu_pages = QtWidgets.QStackedWidget(self.sub_menu_frame)
        self.submenu_pages.setStyleSheet("QPushButton{\n"
"    background-color: rgba(50, 50, 50, 200);\n"
"    padding: 10px;\n"
"    border-radius: 8px;\n"
"    font-size: 10pt;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(29, 29, 29);\n"
"    border-radius: 4px;\n"
"}")
        self.submenu_pages.setObjectName("submenu_pages")
        self.dashboard_menus = QtWidgets.QWidget()
        self.dashboard_menus.setObjectName("dashboard_menus")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.dashboard_menus)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.home_page = QtWidgets.QPushButton(self.dashboard_menus)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.home_page.setFont(font)
        self.home_page.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.home_page.setObjectName("home_page")
        self.verticalLayout_7.addWidget(self.home_page)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem)
        self.submenu_pages.addWidget(self.dashboard_menus)
        self.utilites_menus = QtWidgets.QWidget()
        self.utilites_menus.setObjectName("utilites_menus")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.utilites_menus)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(5)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.numbers_page = QtWidgets.QPushButton(self.utilites_menus)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.numbers_page.setFont(font)
        self.numbers_page.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.numbers_page.setStyleSheet("")
        self.numbers_page.setIcon(icon17)
        self.numbers_page.setIconSize(QtCore.QSize(16, 16))
        self.numbers_page.setObjectName("numbers_page")
        self.verticalLayout_13.addWidget(self.numbers_page)
        self.join_pdf_page = QtWidgets.QPushButton(self.utilites_menus)
        self.join_pdf_page.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.join_pdf_page.setObjectName("join_pdf_page")
        self.verticalLayout_13.addWidget(self.join_pdf_page)
        self.image_extraction_page = QtWidgets.QPushButton(self.utilites_menus)
        self.image_extraction_page.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.image_extraction_page.setObjectName("image_extraction_page")
        self.verticalLayout_13.addWidget(self.image_extraction_page)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem1)
        self.submenu_pages.addWidget(self.utilites_menus)
        self.apis_menus = QtWidgets.QWidget()
        self.apis_menus.setObjectName("apis_menus")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.apis_menus)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.pushButton = QtWidgets.QPushButton(self.apis_menus)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_14.addWidget(self.pushButton)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem2)
        self.submenu_pages.addWidget(self.apis_menus)
        self.tax_menus = QtWidgets.QWidget()
        self.tax_menus.setObjectName("tax_menus")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.tax_menus)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.pan_search_page_btn = QtWidgets.QPushButton(self.tax_menus)
        self.pan_search_page_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pan_search_page_btn.setIcon(icon12)
        self.pan_search_page_btn.setObjectName("pan_search_page_btn")
        self.verticalLayout_15.addWidget(self.pan_search_page_btn)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem3)
        self.submenu_pages.addWidget(self.tax_menus)
        self.lms_menus = QtWidgets.QWidget()
        self.lms_menus.setObjectName("lms_menus")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.lms_menus)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.pushButton_3 = QtWidgets.QPushButton(self.lms_menus)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_16.addWidget(self.pushButton_3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_16.addItem(spacerItem4)
        self.submenu_pages.addWidget(self.lms_menus)
        self.settings_menus = QtWidgets.QWidget()
        self.settings_menus.setObjectName("settings_menus")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.settings_menus)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.pushButton_4 = QtWidgets.QPushButton(self.settings_menus)
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_17.addWidget(self.pushButton_4)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_17.addItem(spacerItem5)
        self.submenu_pages.addWidget(self.settings_menus)
        self.help_menus = QtWidgets.QWidget()
        self.help_menus.setObjectName("help_menus")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.help_menus)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.pushButton_5 = QtWidgets.QPushButton(self.help_menus)
        self.pushButton_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_18.addWidget(self.pushButton_5)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_18.addItem(spacerItem6)
        self.submenu_pages.addWidget(self.help_menus)
        self.about_menus = QtWidgets.QWidget()
        self.about_menus.setObjectName("about_menus")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.about_menus)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.about_app = QtWidgets.QPushButton(self.about_menus)
        self.about_app.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.about_app.setObjectName("about_app")
        self.verticalLayout_19.addWidget(self.about_app)
        self.about_developer = QtWidgets.QPushButton(self.about_menus)
        self.about_developer.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.about_developer.setObjectName("about_developer")
        self.verticalLayout_19.addWidget(self.about_developer)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_19.addItem(spacerItem7)
        self.submenu_pages.addWidget(self.about_menus)
        self.verticalLayout_6.addWidget(self.submenu_pages)
        self.gridLayout.addWidget(self.sub_menu_frame, 1, 1, 2, 1)
        self.right_menu = QtWidgets.QFrame(self.contents)
        self.right_menu.setMinimumSize(QtCore.QSize(175, 0))
        self.right_menu.setMaximumSize(QtCore.QSize(175, 16777215))
        self.right_menu.setStyleSheet("background-color: rgb(37, 37, 38);\n"
"padding: 2px;\n"
"border-bottom-left-radius: 2px;\n"
"border-bottom-right-radius: 2px;\n"
"border-top-right-radius: 2px;")
        self.right_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.right_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_menu.setObjectName("right_menu")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.right_menu)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_3 = QtWidgets.QLabel(self.right_menu)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_12.addWidget(self.label_3)
        self.gridLayout.addWidget(self.right_menu, 0, 3, 3, 1)
        self.verticalLayout.addWidget(self.contents)
        self.credits_bar = QtWidgets.QFrame(self.drop_shadow_frame)
        self.credits_bar.setMinimumSize(QtCore.QSize(0, 30))
        self.credits_bar.setMaximumSize(QtCore.QSize(16777215, 30))
        self.credits_bar.setStyleSheet("background-color: rgb(0, 122, 204);\n"
"border-top-left-radius: 0px;\n"
"border-top-right-radius: 0px;")
        self.credits_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.credits_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.credits_bar.setObjectName("credits_bar")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.credits_bar)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.credit_frame = QtWidgets.QFrame(self.credits_bar)
        self.credit_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.credit_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.credit_frame.setObjectName("credit_frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.credit_frame)
        self.horizontalLayout_4.setContentsMargins(25, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.status_label = QtWidgets.QLabel(self.credit_frame)
        self.status_label.setObjectName("status_label")
        self.horizontalLayout_4.addWidget(self.status_label)
        self.credit_label = QtWidgets.QLabel(self.credit_frame)
        self.credit_label.setMinimumSize(QtCore.QSize(510, 0))
        self.credit_label.setMaximumSize(QtCore.QSize(510, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.credit_label.setFont(font)
        self.credit_label.setStyleSheet("")
        self.credit_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.credit_label.setObjectName("credit_label")
        self.horizontalLayout_4.addWidget(self.credit_label)
        self.horizontalLayout_3.addWidget(self.credit_frame)
        self.grip_frame = QtWidgets.QFrame(self.credits_bar)
        self.grip_frame.setMinimumSize(QtCore.QSize(30, 30))
        self.grip_frame.setMaximumSize(QtCore.QSize(30, 30))
        self.grip_frame.setCursor(QtGui.QCursor(QtCore.Qt.SizeFDiagCursor))
        self.grip_frame.setStyleSheet("padding: 5px;")
        self.grip_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.grip_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.grip_frame.setObjectName("grip_frame")
        self.horizontalLayout_3.addWidget(self.grip_frame)
        self.verticalLayout.addWidget(self.credits_bar)
        self.verticalLayout_26.addWidget(self.drop_shadow_frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.main_content_pages.setCurrentIndex(4)
        self.pan_output.setCurrentIndex(0)
        self.submenu_pages.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Maya Utility App v1.0.0"))
        self.app_title.setText(_translate("MainWindow", "Maya Utility App v1.0.0"))
        self.btn_minimize.setToolTip(_translate("MainWindow", "Minimize"))
        self.btn_minimize.setStatusTip(_translate("MainWindow", "Minimize"))
        self.btn_maximize.setToolTip(_translate("MainWindow", "Maximize"))
        self.btn_maximize.setStatusTip(_translate("MainWindow", "Maximize"))
        self.btn_close.setToolTip(_translate("MainWindow", "Close"))
        self.btn_close.setStatusTip(_translate("MainWindow", "Close"))
        self.settings_menu.setText(_translate("MainWindow", "Settings"))
        self.help_menu.setText(_translate("MainWindow", "Help"))
        self.about_menu.setText(_translate("MainWindow", "About"))
        self.label_2.setText(_translate("MainWindow", "I am a Dashboard UI"))
        self.number_input_label.setText(_translate("MainWindow", "Enter your number:"))
        self.convert_btn.setText(_translate("MainWindow", "Convert"))
        self.decimal_lbl.setText(_translate("MainWindow", "Decimal:"))
        self.eng_lbl.setText(_translate("MainWindow", "English:"))
        self.whole_lbl.setText(_translate("MainWindow", "Whole:"))
        self.words_nep_lbl.setText(_translate("MainWindow", "Words Lakh Nep:"))
        self.lakh_lbl.setText(_translate("MainWindow", "Lakh Format:"))
        self.nepali_lbl.setText(_translate("MainWindow", "Nepali:"))
        self.num_lbl.setText(_translate("MainWindow", "Number:"))
        self.words_eng_lbl.setText(_translate("MainWindow", "Words Million Eng:"))
        self.million_lbl.setText(_translate("MainWindow", "Million Format:"))
        self.add_pdf_files_btn.setText(_translate("MainWindow", "Add Files"))
        self.remove_pdf_file_btn.setText(_translate("MainWindow", "Remove File"))
        self.clear_pdf_btn.setText(_translate("MainWindow", "Clear Files"))
        self.pdf_move_up_btn.setText(_translate("MainWindow", "UP"))
        self.pdf_move_down_btn.setText(_translate("MainWindow", "Down"))
        self.save_pdf_btn.setText(_translate("MainWindow", "Save"))
        self.select_file_btn.setText(_translate("MainWindow", "Either Drop or Select File"))
        self.Image_Label.setText(_translate("MainWindow", "Image will be Shown Here..."))
        self.extracted_texts.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.extracted_texts.setPlaceholderText(_translate("MainWindow", "Your result will be shown Here  "))
        self.pan_input_label.setText(_translate("MainWindow", "Enter your number:"))
        self.clear_pan_btn.setToolTip(_translate("MainWindow", "Clear the Input"))
        self.copy_pan_raw_btn.setToolTip(_translate("MainWindow", "Copy Raw Data"))
        self.pan_search_btn.setToolTip(_translate("MainWindow", "Search the VAT/PAN Number"))
        self.pan_search_btn.setText(_translate("MainWindow", "Search"))
        self.pan_table_output.setSortingEnabled(False)
        item = self.pan_table_output.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name in English"))
        item = self.pan_table_output.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name in Nepali"))
        item = self.pan_table_output.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "VAT/PAN No"))
        item = self.pan_table_output.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Address"))
        item = self.pan_table_output.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "Mobile"))
        item = self.pan_table_output.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "Telephone"))
        item = self.pan_table_output.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "Eff. Reg. Date"))
        item = self.pan_table_output.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "Registered Office"))
        item = self.pan_table_output.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "Personal PAN"))
        item = self.pan_table_output.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "Tax Clearance"))
        item = self.pan_table_output.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "Account Status"))
        item = self.pan_table_output.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "Businesses"))
        item = self.pan_table_output.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Values"))
        __sortingEnabled = self.pan_table_output.isSortingEnabled()
        self.pan_table_output.setSortingEnabled(False)
        self.pan_table_output.setSortingEnabled(__sortingEnabled)
        self.pan_output.setTabText(self.pan_output.indexOf(self.pan_table_output_page), _translate("MainWindow", "PAN/VAT Details"))
        self.raw_pan_output.setText(_translate("MainWindow", "Details will be shown Here!"))
        self.pan_output.setTabText(self.pan_output.indexOf(self.raw_pan_out_page), _translate("MainWindow", "RAW Data"))
        self.welcome_label.setText(_translate("MainWindow", "Good Morning! Ajay Singh"))
        self.quotes_label.setText(_translate("MainWindow", "Turn your wounds into wisdom"))
        self.nepali_date.setText(_translate("MainWindow", "2079-03-22"))
        self.int_date.setText(_translate("MainWindow", "2022-07-06"))
        self.np_cal_btn.setText(_translate("MainWindow", "NP"))
        self.dashboard_menu.setText(_translate("MainWindow", "Dashboard"))
        self.dashboard_menu.setShortcut(_translate("MainWindow", "Ctrl+D"))
        self.utilities_menu.setText(_translate("MainWindow", "Uitlites"))
        self.utilities_menu.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.api_menu.setText(_translate("MainWindow", "API"))
        self.api_menu.setShortcut(_translate("MainWindow", "Ctrl+A"))
        self.tax_menu.setText(_translate("MainWindow", "TAX"))
        self.tax_menu.setShortcut(_translate("MainWindow", "Ctrl+T"))
        self.lms_menu.setText(_translate("MainWindow", "Library"))
        self.lms_menu.setShortcut(_translate("MainWindow", "Ctrl+L"))
        self.home_page.setText(_translate("MainWindow", "Home"))
        self.numbers_page.setText(_translate("MainWindow", "Numbers"))
        self.join_pdf_page.setText(_translate("MainWindow", "PDF Join"))
        self.image_extraction_page.setText(_translate("MainWindow", "Text Extraction"))
        self.pushButton.setText(_translate("MainWindow", "APiS"))
        self.pan_search_page_btn.setText(_translate("MainWindow", " Pan Search"))
        self.pushButton_3.setText(_translate("MainWindow", "Library"))
        self.pushButton_4.setText(_translate("MainWindow", "Settings"))
        self.pushButton_5.setText(_translate("MainWindow", "Help"))
        self.about_app.setText(_translate("MainWindow", "About App"))
        self.about_developer.setText(_translate("MainWindow", "About Developer"))
        self.label_3.setText(_translate("MainWindow", "Right - Side -Menu"))
        self.status_label.setText(_translate("MainWindow", "Ready"))
        self.credit_label.setText(_translate("MainWindow", "Copyright @ Ajay Singh [Maya] 2022. All the rights are reserved."))
from widgets.DropZone import DropZone
import assets_rc
